name: MF Merge from Develop

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:


jobs:

  merge-from-develop:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Merge from Develop to PR
      uses: maven-flow/merge@v1
      with:
        changelog-rebase: true
        source-branch: develop
        target-branch: ${{ github.head_ref }}
